"""Inject "Open in Google Colab" links into every README (idempotent).

Run:  python tools/add_colab_links.py

For each chapter folder it inserts a "Run in Google Colab" block listing that
chapter's notebooks, and it rebuilds a master list in the root README. The block
is wrapped in marker comments so re-running just replaces it (safe to run again
whenever notebooks are added).
"""
import glob
import os
import re

# --- repo coordinates: change these if you fork/rename the repo ---
REPO = "cto-school/mathematics-for-machine-learning"
BRANCH = "main"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

START = "<!-- COLAB-LINKS:START (auto-generated by tools/add_colab_links.py) -->"
END = "<!-- COLAB-LINKS:END -->"


def colab_url(path_rel):
    """A Colab URL opens the notebook straight from GitHub."""
    return f"https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{path_rel}"


def chapter_dirs():
    out = []
    for name in sorted(os.listdir(ROOT)):
        if os.path.isdir(os.path.join(ROOT, name)) and re.match(r"^\d\d-", name):
            out.append(name)
    return out


def notebooks_in(chap):
    paths = glob.glob(os.path.join(ROOT, chap, "*.ipynb"))
    return sorted(os.path.basename(p) for p in paths)


def upsert(text, block, fallback_before=None):
    """Replace the marked block if present; otherwise insert it.

    Insert position: just before the heading `fallback_before` if given and
    found, else right after the first level-1 heading.
    """
    wrapped = START + "\n" + block + "\n" + END
    if START in text and END in text:
        return re.sub(re.escape(START) + r".*?" + re.escape(END),
                      lambda _m: wrapped, text, flags=re.S)

    lines = text.split("\n")
    if fallback_before:
        for i, ln in enumerate(lines):
            if ln.strip() == fallback_before:
                lines[i:i] = [wrapped, ""]
                return "\n".join(lines)
    for i, ln in enumerate(lines):
        if ln.startswith("# "):
            lines[i + 1:i + 1] = ["", wrapped]
            return "\n".join(lines)
    return wrapped + "\n\n" + text


def chapter_block(chap, nbs):
    lines = ["## ▶ Run in Google Colab", "",
             "Click a badge to open the notebook in your browser — no install needed.",
             ""]
    for nb in nbs:
        url = colab_url(f"{chap}/{nb}")
        lines.append(f"- `{nb}` &nbsp; [![Open In Colab]({BADGE})]({url})")
    return "\n".join(lines)


def root_block():
    lines = ["## ▶ Open in Google Colab", "",
             "Every notebook runs in the browser with **zero setup** — just click "
             "a badge (a free Google account is all you need). Or open any chapter "
             "folder's README for its own links.", ""]
    for chap in chapter_dirs():
        nbs = notebooks_in(chap)
        if not nbs:
            continue
        lines.append(f"**{chap}**  ")
        for nb in nbs:
            url = colab_url(f"{chap}/{nb}")
            lines.append(f"&nbsp;&nbsp;`{nb}` [![Open In Colab]({BADGE})]({url})  ")
        lines.append("")
    return "\n".join(lines).rstrip()


def main():
    # 1) each chapter README
    for chap in chapter_dirs():
        nbs = notebooks_in(chap)
        if not nbs:
            continue
        path = os.path.join(ROOT, chap, "README.md")
        if not os.path.exists(path):
            print("skip (no README):", chap)
            continue
        text = open(path, encoding="utf-8").read()
        new = upsert(text, chapter_block(chap, nbs))
        if new != text:
            open(path, "w", encoding="utf-8").write(new)
        print("updated", chap, "README")

    # 2) root README (place the master list right before the Curriculum section)
    root_readme = os.path.join(ROOT, "README.md")
    text = open(root_readme, encoding="utf-8").read()
    new = upsert(text, root_block(), fallback_before="## Curriculum")
    if new != text:
        open(root_readme, "w", encoding="utf-8").write(new)
    print("updated root README")


if __name__ == "__main__":
    main()
